#!/bin/bash
rm -f dist/m4b-tool* bin/*.log


if [[ "$1" == "--with-plugins" ]]; then
    echo "!!! WITH PLUGINS !!!";
    PHP_CODE="echo '';"
else
    PHP_CODE="try {\
    \$p = 'phar://'.realpath(__DIR__.'/dist/m4b-tool.phar').'/src/library/Command/Plugins/'; \
    \$f = new Phar(\$p);\
    foreach(\$f as \$file) {\
    unlink(\$file);\
    }\
    } catch(Throwable \$e) {}";
fi

php -d phar.readonly=off tools/box.phar build && php -d phar.readonly=off -r "${PHP_CODE}" && chmod +x dist/*.phar && tar -C dist -czf dist/m4b-tool.tar.gz m4b-tool.phar && cd dist && zip m4b-tool.zip m4b-tool.phar && cd -
