#!/bin/bash

# CONFIG SECTION - CHANGE ACCORDING YOUR NEEDS
INPUT_DIR="input"                   # Existing structure: input/<author>/<title>/*.mp3, e.g. input/J.K. Rowling/Harry Potter (1) - and the Philosopher’s Stone/*.mp3
OUTPUT_DIR="output"                 # Generated structure: output/<author>/<name>/<name> [(<number>)] - <title>.m4b, e.g. output/J.K. Rowling/Harry Potter/Harry Potter (1) - and the Philosopher’s Stone.m4b
M4B_TOOL="/usr/local/bin/m4b-tool"  # To make m4b-tool.phar executable: sudo cp m4b-tool.phar /usr/local/bin/m4b-tool && sudo chmod +x /usr/local/bin/m4b-tool
AUTOSPLIT_SECONDS=720               # Tracks to merge can be a maximum length of 12 minutes, if using the title as chapter, otherwise, they will be splitted into multiple parts
ADJUST_FOR_IPOD=1                   # if audiobook is too long with the given settings for bitrate and samplerate, it will be auto downsampled
AUDIO_CHANNELS=1
AUDIO_BITRATE="64k"
AUDIO_SAMPLERATE=22050


# EXECUTION SECTION - ONLY MODIFY IF YOU KNOW WHAT YOU ARE DOING
SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

for D in `find $INPUT_DIR/*/*/ -maxdepth 0 -type d`
do
        NAME="$(echo ${D/$INPUT_DIR/} | sed -e 's/^\/*//')";
        AUTHOR="$(dirname $NAME)"
        TITLE="$(basename $NAME)"
        SERIES="$(echo $TITLE | cut -d'(' -f 1 | sed -e 's/[[:space:]]*$//')"

#	echo "NAME: $NAME"
#	echo "AUTH: $AUTHOR"
#	echo "TITL: $TITLE"
#	echo "SERI: $SERIES"
#	exit;

        CURRENT_OUTPUT_DIR="$OUTPUT_DIR/$AUTHOR/$SERIES"
        CURRENT_OUTPUT_FILE="$CURRENT_OUTPUT_DIR/$TITLE.m4b"
        CURRENT_CHAPTERS_FILE="$CURRENT_OUTPUT_DIR/$TITLE.chapters.txt"

        if [ -f "$CURRENT_OUTPUT_FILE" ]; then
                echo "- $TITLE already exists - skipping"
                continue
        fi

        if [ -d "$CURRENT_OUTPUT_DIR" ]; then
                mkdir -p "$CURRENT_OUTPUT_DIR"
        fi

        if [ "1" == "$ADJUST_FOR_IPOD" ]; then
            $M4B_TOOL merge --auto-split-seconds=$AUTOSPLIT_SECONDS --adjust-for-ipod --name "$TITLE" --album="$TITLE" --audio-channels $AUDIO_CHANNELS --audio-bitrate $AUDIO_BITRATE --audio-samplerate $AUDIO_SAMPLERATE --audio-codec libfdk_aac "$D" --output-file="$CURRENT_OUTPUT_FILE" && echo "$NAME" >> multi-convert.log
        else
            $M4B_TOOL merge --auto-split-seconds=$AUTOSPLIT_SECONDS --name "$TITLE" --album="$TITLE" --audio-channels $AUDIO_CHANNELS --audio-bitrate $AUDIO_BITRATE --audio-samplerate $AUDIO_SAMPLERATE --audio-codec libfdk_aac "$D" --output-file="$CURRENT_OUTPUT_FILE" && echo "$NAME" >> multi-convert.log
        fi

        if [ -f "$CURRENT_CHAPTERS_FILE" ]; then
                rm "$CURRENT_CHAPTERS_FILE"
        fi
done
IFS=$SAVEIFS